services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.3-cli}
    volumes:
      - .:/app
    working_dir: /app

  mysql:
    image: mysql:8.0
    healthcheck:
      test: ["CMD-SHELL", "mysql -h mysql --user=root --password=$${MYSQL_ROOT_PASSWORD} -e status"]
      interval: 10s
      timeout: 2s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: l_test
      MYSQL_USER: l_user
      MYSQL_PASSWORD: l_password
